Traceback (most recent call last):
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from plotnine import geom_density
from plotnine.data import mpg
(
    ggplot(mpg, aes(x='cty', color='drv', fill='drv'))
    + geom_density(
        aes(y=after_stat('count')),
        alpha=0.1
    )
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-31-5aec4163f194>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m     [0mggplot[0m[0;34m([0m[0mmpg[0m[0;34m,[0m [0maes[0m[0;34m([0m[0mx[0m[0;34m=[0m[0;34m'cty'[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m'drv'[0m[0;34m,[0m [0mfill[0m[0;34m=[0m[0;34m'drv'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     + geom_density(
[0;32m----> 6[0;31m         [0maes[0m[0;34m([0m[0my[0m[0;34m=[0m[0mafter_stat[0m[0;34m([0m[0;34m'count'[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m         [0malpha[0m[0;34m=[0m[0;36m0.1[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m     )

[0;31mNameError[0m: name 'after_stat' is not defined
NameError: name 'after_stat' is not defined

