Traceback (most recent call last):
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aet/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.loc[::10, 'name':'birth_year']
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   2894[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2895[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2896[0m             [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32mpandas/_libs/index.pyx[0m in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

[0;32mpandas/_libs/index.pyx[0m in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

[0;32mpandas/_libs/hashtable_class_helper.pxi[0m in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;32mpandas/_libs/hashtable_class_helper.pxi[0m in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'birth_year'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-5-f99cd628d4c8>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0;34m:[0m[0;34m:[0m[0;36m10[0m[0;34m,[0m [0;34m'name'[0m[0;34m:[0m[0;34m'birth_year'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    871[0m                     [0;31m# AttributeError for IntervalTree get_value[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    872[0m                     [0;32mpass[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 873[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_tuple[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    874[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    875[0m             [0;31m# we by definition only have the 0th axis[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_tuple[0;34m(self, tup)[0m
[1;32m   1053[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_multi_take[0m[0;34m([0m[0mtup[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1054[0m [0;34m[0m[0m
[0;32m-> 1055[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_tuple_same_dim[0m[0;34m([0m[0mtup[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1056[0m [0;34m[0m[0m
[1;32m   1057[0m     [0;32mdef[0m [0m_get_label[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mlabel[0m[0;34m,[0m [0maxis[0m[0;34m:[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_tuple_same_dim[0;34m(self, tup)[0m
[1;32m    748[0m                 [0;32mcontinue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    749[0m [0;34m[0m[0m
[0;32m--> 750[0;31m             [0mretval[0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0mretval[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mname[0m[0;34m)[0m[0;34m.[0m[0m_getitem_axis[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0mi[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    751[0m             [0;31m# We should never have retval.ndim < self.ndim, as that should[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    752[0m             [0;31m#  be handled by the _getitem_lowerdim call above.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1086[0m         [0;32mif[0m [0misinstance[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mslice[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1087[0m             [0mself[0m[0;34m.[0m[0m_validate_key[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1088[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_slice_axis[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1089[0m         [0;32melif[0m [0mcom[0m[0;34m.[0m[0mis_bool_indexer[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1090[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getbool_axis[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_get_slice_axis[0;34m(self, slice_obj, axis)[0m
[1;32m   1120[0m [0;34m[0m[0m
[1;32m   1121[0m         [0mlabels[0m [0;34m=[0m [0mobj[0m[0;34m.[0m[0m_get_axis[0m[0;34m([0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1122[0;31m         indexer = labels.slice_indexer(
[0m[1;32m   1123[0m             [0mslice_obj[0m[0;34m.[0m[0mstart[0m[0;34m,[0m [0mslice_obj[0m[0;34m.[0m[0mstop[0m[0;34m,[0m [0mslice_obj[0m[0;34m.[0m[0mstep[0m[0;34m,[0m [0mkind[0m[0;34m=[0m[0;34m"loc"[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1124[0m         )

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mslice_indexer[0;34m(self, start, end, step, kind)[0m
[1;32m   4964[0m         [0mslice[0m[0;34m([0m[0;36m1[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0;32mNone[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   4965[0m         """
[0;32m-> 4966[0;31m         [0mstart_slice[0m[0;34m,[0m [0mend_slice[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mslice_locs[0m[0;34m([0m[0mstart[0m[0;34m,[0m [0mend[0m[0;34m,[0m [0mstep[0m[0;34m=[0m[0mstep[0m[0;34m,[0m [0mkind[0m[0;34m=[0m[0mkind[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   4967[0m [0;34m[0m[0m
[1;32m   4968[0m         [0;31m# return a slice[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mslice_locs[0;34m(self, start, end, step, kind)[0m
[1;32m   5173[0m         [0mend_slice[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5174[0m         [0;32mif[0m [0mend[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5175[0;31m             [0mend_slice[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mget_slice_bound[0m[0;34m([0m[0mend[0m[0;34m,[0m [0;34m"right"[0m[0;34m,[0m [0mkind[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5176[0m         [0;32mif[0m [0mend_slice[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5177[0m             [0mend_slice[0m [0;34m=[0m [0mlen[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_slice_bound[0;34m(self, label, side, kind)[0m
[1;32m   5087[0m             [0;32mexcept[0m [0mValueError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5088[0m                 [0;31m# raise the original KeyError[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5089[0;31m                 [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5090[0m [0;34m[0m[0m
[1;32m   5091[0m         [0;32mif[0m [0misinstance[0m[0;34m([0m[0mslc[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mndarray[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_slice_bound[0;34m(self, label, side, kind)[0m
[1;32m   5081[0m         [0;31m# we need to look up the label[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5082[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5083[0;31m             [0mslc[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mlabel[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5084[0m         [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5085[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   2895[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2896[0m             [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2897[0;31m                 [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m [0;32mfrom[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2898[0m [0;34m[0m[0m
[1;32m   2899[0m         [0;32mif[0m [0mtolerance[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'birth_year'
KeyError: 'birth_year'

